name: Web App
on: 
  push:
    branches: [assignment4]
jobs:
  packer_validate:
    runs-on: ubuntu-latest
    name: Validate Template
    steps:
      - name: Step 1 - Checkout code
        uses: actions/checkout@v2

      - name: Step 2 - Packer Init
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: application-ami.pkr.hcl

      - name: Step 3 - Packer Validate
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -var-file=variables.pkrvars.hcl
          target: application-ami.pkr.hcl
  create_artifact:
    needs: packer_validate
    runs-on: ubuntu-latest
    name: My Artifact
    steps:
      - name: Step 1 - Checkout code
        uses: actions/checkout@v2

      - name: Step 2 - Upload Artifact github action
        uses: actions/upload-artifact@v2
        with:
          name: webapp_artifact
          path: origin/assignment4
      
      - name: Step 3 - ls
        run: sudo ls -a
