name: Web App
on: 
  push:
    branches: [assignment4]
jobs:
  packer_validate:
    runs-on: ubuntu-latest
    name: Validate Template
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Packer Init
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: application-ami.pkr.hcl

      - name: Packer Validate
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -var-file="variables.pkrvars.hcl"
          target: application-ami.pkr.hcl
