name: Web App
on: 
  push:
    branches: [assignment4]
jobs:
  packer_validate:
    runs-on: ubuntu-latest
    name: Validate Template
    steps:
      - name: Step 1 - Checkout code
        uses: actions/checkout@v2

      - name: Step 2 - Packer Init
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: application-ami.pkr.hcl

      - name: Step 3 - Packer Validate
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -var-file=variables.pkrvars.hcl
          target: application-ami.pkr.hcl
  create_artifact:
    needs: packer_validate
    runs-on: ubuntu-latest
    name: My Artifact
    steps:
      - name: Step 1 - Checkout code
        uses: actions/checkout@v2

      - name: zip files
        run: |
          zip webservice ../webservice

      - name: Step 4 - ls
        run: ls -a

      - name: unzip to check
        uses: montudor/action-zip@v1
        with:
          args: unzip -qq webservice.zip -d webservice

      - name: check if zipped correctly
        run: |
          cd webservice
          ls -a