name: Test APIs
on: [push]
jobs:
  check-api:
    name: Check all apis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.2'

      - name: Install dependencies
        run: npm ci
      - name: Run Api Tests
        run:  npm run test
