name: Deploy Web App

env:
  # environment vars
  ARTIFACT_NAME: webservice-${{ github.sha }}

on: 
  push:
    branches: [assignment7]

jobs:
  code_deploy:
    runs-on: ubuntu-latest
    name: Run CodeDeploy
    steps:
      - name: Step 1 - Checkout code
        uses: actions/checkout@v2

      - name: Step 2 - Install AWS Cli
        run: sudo pip install awscli

      - name: Step 3 - Set correct aws environment
        run: |
          aws configure set region us-east-1
          aws configure set aws_access_key_id ${{ secrets.AWS_GHUSER_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_GHUSER_SECRET_ACCESS_KEY }}

      # - name: Step 4 - Create Deployment Artifact/zip
      #   run: |
      #     echo "Creating zip and building zip version ${{ github.sha }}"
      #     pwd
      #     ls -al
      #     mkdir codedeploy_artifact
      #     pwd
      #     ls -al
      #     zip -r ${{ env.ARTIFACT_NAME }}.zip ./
      #     ls -al
      #     mv ${{ env.ARTIFACT_NAME }}.zip codedeploy_artifact
      #     pwd
      #     cd codedeploy_artifact
      #     pwd
      #     ls -al
      #     cd ..
      #     pwd
      #     ls -al
      #     echo "Created artifact ${{ env.ARTIFACT_NAME }}"
      # aws s3 sync ./codedeploy_artifact s3://${{ secrets.AWS_BUCKET }}/deploy/
 
      - name: Step 4 - Upload Artifact/zip files to s3 bucket
        run: |
          aws deploy push --application-name csye6225-webapp --s3-location s3://${{ secrets.AWS_BUCKET }}/${{ env.ARTIFACT_NAME }}.zip
      
      - name: Step 5 - Create Deployment
        run: |
          aws deploy create-deployment --application-name csye6225-webapp --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name csye6225-webapp-deployment --s3-location bucket=${S3_BUCKET_ADDR},bundleType=zip,key=deployments/csye6225-web-app-${CIRCLE_BUILD_NUM}.zip
          aws deploy create-deployment \
          --application-name csye6225-webapp \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name csye6225-webapp-deployment \
          --s3-location bucket=${{ secrets.AWS_BUCKET }},key=${{ env.ARTIFACT_NAME }}.zip,bundleType=zip