name: Deploy Web App
on: 
  push:
    branches: [assignment7]
jobs:
  code_deploy:
    runs-on: ubuntu-latest
    name: Run CodeDeploy
    steps:
      - name: Step 1 - Checkout code
        uses: actions/checkout@v2

      - name: Step 2 - Install AWS Cli
        run: sudo pip install awscli

      - name: Step 3 - Set correct environment
        run: |
          aws configure set region us-east-1
          aws configure set aws_access_key_id ${{ secrets.AWS_PROD_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}

      - name: Step 4 - Create Artifact/zip
        run: |
          zip -r webservice.zip ./
 
      # - name: Step 5 - Upload Artifact/zip files to s3 bucket
      #   run: |
      #     aws s3 cp ./webservice.zip s3://${{ secrets.AWS_BUCKET }}/deploy/webservice.zip